version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - pg-storage:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server --console-address ":9001" /data/
    env_file: .env
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ..
      dockerfile: deployments/server.Dockerfile
    container_name: server
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_healthy

  nginx:
    image: nginx-custom:latest
    build:
      context: ..
      dockerfile: deployments/nginx.Dockerfile
    restart: unless-stopped
    tty: true
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    depends_on:
      - server

volumes:
  minio-storage:
  pg-storage: