db:
  host: database
  port: 5432
  db_name: postgres
  sslmode: disable
  env_user: POSTGRES_USER
  env_password: POSTGRES_PASSWORD
  driver_name: postgres

http:
  addr: :8080

period_for_deleting_inactive_segments:
  cron_expression: "0 * * * *" # every hour